{
    'name': 'DLM-ERP Cấu hình (Master Data)',
    'version': '17.0.1.0.0',
    'summary': 'Master Data: Tiền tệ, Đơn vị tính, Thuế VAT, Công ty — Phase 1',
    'author': 'Dai Linh',
    'category': 'Hidden',
    # uom/account: chứa model uom.uom/account.tax mà module dựng UI lên (không tạo model mới)
    'depends': ['dl_base', 'dl_sale', 'uom', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'views/config_home.xml',
        'views/currency_views.xml',
        'views/uom_views.xml',
        'views/company_views.xml',
        'views/vat_views.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'dl_config/static/src/js/nav_patch.js',
            'dl_config/static/src/scss/control_panel.scss',
            'dl_config/static/src/components/config_home/config_home.scss',
            'dl_config/static/src/components/config_home/config_home.xml',
            'dl_config/static/src/components/config_home/config_home.js',
            'dl_config/static/src/scss/currency_list.scss',
            'dl_config/static/src/scss/currency_form.scss',
            'dl_config/static/src/views/currency_list_controller.js',
            'dl_config/static/src/views/currency_form_controller.js',
            'dl_config/static/src/scss/uom_list.scss',
            'dl_config/static/src/scss/uom_form.scss',
            'dl_config/static/src/views/uom_list_controller.js',
            'dl_config/static/src/views/uom_form_controller.js',
            'dl_config/static/src/scss/company_list.scss',
            'dl_config/static/src/scss/company_form.scss',
            'dl_config/static/src/views/company_list_controller.js',
            'dl_config/static/src/scss/vat_list.scss',
            'dl_config/static/src/scss/vat_form.scss',
            'dl_config/static/src/views/vat_list_controller.js',
            'dl_config/static/src/views/vat_form_controller.js',
        ],
    },
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
