{
    'name': 'DLM-ERP Cấu hình (Master Data)',
    'version': '17.0.2.1.0',
    'summary': 'Cấu hình hệ thống, cấu hình báo giá có phiên bản và dữ liệu danh mục',
    'author': 'Dai Linh',
    'category': 'Hidden',
    # uom: chứa model uom.uom mà module dựng UI lên (không tạo model mới)
    # auth_signup: cung cấp action_reset_password() + email template + trang đặt mật khẩu
    'depends': ['dl_base', 'uom', 'auth_signup', 'mail', 'product'],
    'data': [
        'security/ir.model.access.csv',
        'security/pricing_record_rules.xml',
        'data/rbac_features.xml',
        'data/pricing_config_data.xml',
        'data/pricing_seed.xml',
        'views/config_home.xml',
        'views/uom_views.xml',
        'views/company_views.xml',
        'views/user_admin_views.xml',
        'views/role_perm_views.xml',
        'views/pricing_config_views.xml',
        'views/pricing_matrix_views.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'dl_config/static/src/js/nav_patch.js',
            'dl_config/static/src/scss/control_panel.scss',
            'dl_config/static/src/components/config_home/config_home.scss',
            'dl_config/static/src/components/config_home/config_home.xml',
            'dl_config/static/src/components/config_home/config_home.js',
            # S01 — Quản lý User & Phân quyền (OWL mock)
            'dl_config/static/src/components/user_admin/user_admin.scss',
            'dl_config/static/src/components/user_admin/user_admin.xml',
            'dl_config/static/src/components/user_admin/user_admin.js',
            # Phân quyền Vai trò (OWL, nối DB thật — RBAC)
            'dl_config/static/src/components/role_perm/role_perm.scss',
            'dl_config/static/src/components/role_perm/role_perm.xml',
            'dl_config/static/src/components/role_perm/role_perm.js',
            # S02 — Cấu hình Hệ thống (OWL mock)
            'dl_config/static/src/components/sys_config/sys_config.scss',
            'dl_config/static/src/components/sys_config/sys_config.xml',
            'dl_config/static/src/components/sys_config/sys_config.js',
            # Cấu hình Báo giá (V3) — màn OWL nhiều tab, nối model quy tắc thật.
            'dl_config/static/src/components/pricing_config/pricing_config.scss',
            'dl_config/static/src/components/pricing_config/pricing_config.xml',
            'dl_config/static/src/components/pricing_config/pricing_config.js',
            'dl_config/static/src/scss/uom_list.scss',
            'dl_config/static/src/scss/uom_form.scss',
            'dl_config/static/src/views/uom_list_controller.js',
            'dl_config/static/src/views/uom_form_controller.js',
            'dl_config/static/src/scss/company_list.scss',
            'dl_config/static/src/scss/company_form.scss',
            'dl_config/static/src/views/company_list_controller.js',
            'dl_config/static/src/views/company_form_controller.js',
        ],
    },
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
