{
    'name': 'DLM-ERP Kỹ thuật — BOM (S08)',
    'version': '17.0.1.0.0',
    'summary': 'Quản lý BOM & BOM Mẫu, Bản vẽ, RFQ kỹ thuật — Phase 1 (S08)',
    'author': 'Dai Linh',
    'category': 'Hidden',
    'depends': ['dl_base', 'dlm_material', 'dl_sale', 'mail', 'uom'],
    'external_dependencies': {'python': ['simpleeval']},
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/product_views.xml',
        'views/drawing_views.xml',
        'views/parametric_formula_views.xml',
        'views/bom_views.xml',
        'views/quotation_request_views.xml',
        'views/technical_home.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'dl_bom/static/src/components/technical_home/technical_home.scss',
            'dl_bom/static/src/components/technical_home/technical_home.xml',
            'dl_bom/static/src/components/technical_home/technical_home.js',
            'dl_bom/static/src/js/nav_patch.js',
        ],
    },
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
