{
    "name": "DL-Technical",
    "version": "17.0.1.0.0",
    "summary": "Quản lý BOM, Bản vẽ, Bán thành phẩm, công thức",
    "author": "Dai Linh",
    "category": "Hidden",
    "depends": ["dl_base", "dl_product", "uom"],
    "external_dependencies": {"python": ["simpleeval"]},
    "data": [
        "security/ir.model.access.csv",
        "data/rbac_features.xml",
        "data/ir_sequence_data.xml",
        "views/product_views.xml",
        "views/drawing_views.xml",
        "views/parametric_formula_views.xml",
        "views/bom_views.xml",
        "views/quotation_request_views.xml",
        "views/technical_home.xml",
        "views/menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            # Đồng bộ UI danh sách/form với các màn dl_sale/dl_product.
            "dl_technical/static/src/scss/bom_list.scss",
            "dl_technical/static/src/scss/bom_form.scss",
            "dl_technical/static/src/scss/rfq_list.scss",
            "dl_technical/static/src/scss/rfq_form.scss",
            "dl_technical/static/src/scss/drawing_list.scss",
            "dl_technical/static/src/scss/drawing_form.scss",
            "dl_technical/static/src/views/bom_list_controller.js",
            "dl_technical/static/src/views/bom_form_controller.js",
            "dl_technical/static/src/views/rfq_list_controller.js",
            "dl_technical/static/src/views/rfq_form_controller.js",
            "dl_technical/static/src/views/drawing_list_controller.js",
            "dl_technical/static/src/views/drawing_form_controller.js",
            # Dashboard "Kỹ thuật"
            "dl_technical/static/src/components/technical_home/technical_home.scss",
            "dl_technical/static/src/components/technical_home/technical_home.xml",
            "dl_technical/static/src/components/technical_home/technical_home.js",
        ],
    },
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
