{
    "name": "DL-Technical",
    "version": "17.0.1.15.0",
    "summary": "Quản lý BOM, Bản vẽ, Bán thành phẩm, công thức",
    "author": "Dai Linh",
    "category": "Hidden",
    "depends": ["dl_base", "dl_product", "dl_partner", "uom", "dl_config"],
    "data": [
        "security/ir.model.access.csv",
        "data/rbac_features.xml",
        "data/ir_sequence_data.xml",
        "data/measurement_shape_data.xml",
        "data/rfq_provisional_data.xml",
        "views/product_views.xml",
        "views/drawing_views.xml",
        "views/bom_views.xml",
        "views/bom_template_views.xml",
        "views/quotation_request_views.xml",
        "wizard/rfq_resolve_wizard_views.xml",
        "wizard/rfq_line_quick_wizard_views.xml",
        "wizard/rfq_return_wizard_views.xml",
        "wizard/rfq_history_wizard_views.xml",
        "wizard/bom_from_template_wizard_views.xml",
        "views/technical_home.xml",
        "views/menus.xml",
        "data/dl_demo_data.xml",
    ],
    "assets": {
        "web.assets_backend": [
            # Đồng bộ UI danh sách/form với các màn dl_sale/dl_product.
            "dl_technical/static/src/scss/bom_list.scss",
            "dl_technical/static/src/scss/rfq_list.scss",
            "dl_technical/static/src/scss/rfq_resolve.scss",
            "dl_technical/static/src/scss/rfq_history.scss",
            "dl_technical/static/src/scss/drawing_list.scss",
            "dl_technical/static/src/scss/drawing_form.scss",
            "dl_technical/static/src/views/bom_list_controller.js",
            "dl_technical/static/src/views/bom_form_controller.js",
            "dl_technical/static/src/views/drawing_preview_field.js",
            "dl_technical/static/src/views/drawing_preview_field.xml",
            "dl_technical/static/src/views/drawing_preview_field.scss",
            "dl_technical/static/src/views/drawing_upload_field.js",
            "dl_technical/static/src/views/drawing_upload_field.xml",
            "dl_technical/static/src/views/drawing_upload_field.scss",
            "dl_technical/static/src/views/rfq_list_controller.js",
            "dl_technical/static/src/views/rfq_form_controller.js",
            "dl_technical/static/src/views/drawing_list_controller.js",
            "dl_technical/static/src/views/drawing_form_controller.js",
            "dl_technical/static/src/views/bomtpl_form_controller.js",
            # Dashboard "Kỹ thuật"
            "dl_technical/static/src/components/technical_home/technical_home.scss",
            "dl_technical/static/src/components/technical_home/technical_home.xml",
            "dl_technical/static/src/components/technical_home/technical_home.js",
            "dl_technical/static/src/js/nav_patch.js",
        ],
    },
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
