# -*- coding: utf-8 -*-
"""Bảng 'Data Constraints & Conditions' — nhóm D, E, F."""

DCC = {}

# ══════════════════════════════ NHÓM D ═══════════════════════════════════════

DCC["dl_quotation"] = [
    ["name", "Uniqueness", "Quotation number generated by ir.sequence; unique per company."],
    ["date_order, validity_date", "Date order",
     "The validity date may not fall before the quotation date."],
    ["state", "State machine",
     "draft → approved → sent → accepted → ordered, with the side exits revision_requested, "
     "rejected, expired and cancelled. Every transition below is guarded; see §3.3 for the "
     "value list."],
    ["approval_state", "State machine",
     "not_required / pending / approved / rejected, default 'not_required'. Set by the approval "
     "matrix from the order value, the discount and the floor price."],
    ["action_approve()", "Action guard",
     "Internal approval only from Draft. Refused while an approval request is still pending, and "
     "refused after a rejection until the quotation has been edited and re-evaluated."],
    ["_check_internal_approver()", "Access guard",
     "Only CEO, Sales Manager, Admin, or a user explicitly granted the “Duyệt báo giá” operation."],
    ["action_send()", "Action guard",
     "Sending to the customer is refused while approval is pending, after a rejection, and when "
     "approval is required but not yet granted."],
    ["action_customer_accept()", "Action guard",
     "Acceptance may only be recorded on a quotation that was actually sent."],
    ["action_customer_withdraw()", "Action guard",
     "Withdrawal only from Accepted, and only while no sales order exists yet."],
    ["action_open_revision_wizard()", "Action guard",
     "A revision request may only be recorded on a quotation already sent to the customer."],
    ["action_send_back_to_tech()", "Action guard",
     "Only from 'revision_requested', and only when the quotation has a source RFQ; otherwise the "
     "user is told to use “Sửa & gửi lại”."],
    ["action_expire() / action_reopen()", "Action guard",
     "Expiry applies to Approved / Sent / Revision-requested. Re-opening applies only to an "
     "expired quotation and requires a validity date in the future."],
    ["action_create_revision()", "Action guard",
     "A new version may be raised from Sent / Revision-requested / Rejected / Expired only."],
    ["action_reset_draft()", "Action guard",
     "Back to draft from Approved / Sent / Revision-requested / Rejected / Expired."],
    ["action_create_sale_order()", "Action guard",
     "A sales order may only be created once the customer has accepted."],
    ["—", "Snapshot rule",
     "Giá đã tính được đóng băng ở dl_quotation_price_component. Bảng giá NCC hay tham số cấu "
     "hình đổi về sau KHÔNG làm đổi báo giá đã gửi — đây là điều kiện để một báo giá cũ còn tái "
     "lập được."],
]

DCC["dl_quotation_line"] = [
    ["quotation_id", "Referential", "NOT NULL, ON DELETE CASCADE — lines die with the quotation."],
    ["line_type", "Enum", "trading / manufactured, default 'trading'. See §3.3."],
    ["quantity", "Range", "Must be strictly greater than 0."],
    ["—", "Visibility rule",
     "Bảng này giữ CẢ giá bán lẫn giá vốn/giá sàn. Cột giá vốn bị ẩn khỏi vai trò Kỹ thuật viên "
     "ở tầng giao diện và chặn thật ở tầng ir.rule — xem §4."],
    ["—", "Derived",
     "Đơn giá lấy từ engine tính giá tại thời điểm tính, không nhập tay; người dùng chỉ được "
     "điều chỉnh trong biên độ chiết khấu mà chính sách cho phép."],
]

DCC["dl_quotation_price_component"] = [
    ["quotation_id", "Referential", "NOT NULL, ON DELETE CASCADE, INDEX."],
    ["quotation_line_id", "Referential", "ON DELETE CASCADE, INDEX."],
    ["component_type", "Enum required",
     "trading_base / material / processed_material / recovery / operation / overhead / margin / "
     "discount … — see §3.3."],
    ["—", "Immutability",
     "Snapshot: các dòng thành phần giá KHÔNG có màn hình sửa. Chúng được engine ghi một lần khi "
     "tính giá và chỉ bị xoá khi tính lại toàn bộ báo giá."],
    ["—", "Audit purpose",
     "Đây là bảng trả lời câu hỏi “vì sao báo giá này ra con số đó” — thiếu nó thì một báo giá "
     "sáu tháng trước không giải thích được."],
]

DCC["dl_sale_order"] = [
    ["name", "Uniqueness", "Order number generated by ir.sequence."],
    ["quotation_id", "Referential",
     "ON DELETE RESTRICT, INDEX — a quotation that produced an order cannot be deleted."],
    ["date_order, quotation_id", "Date order",
     "The order date may not fall before the date of the source quotation."],
    ["state", "State machine", "draft → confirmed → done, plus cancelled. See §3.3."],
    ["partner_id", "CRUD guard",
     "write() refuses to change the customer once the order was locked in from a quotation, or "
     "once it left Draft. The user is told to create a new order from the relevant quotation."],
    ["_check_can_reset_draft()", "Action guard",
     "An order created from a customer-accepted quotation may NOT be reset to draft — the user "
     "must cancel it, raise a quotation revision and create a new order. Only a direct sale still "
     "in Confirmed may go back."],
    ["_reset_to_draft_with_reason()", "Required",
     "Resetting to draft requires a written reason."],
    ["_dlm_check_delivery_allowed()", "Action guard",
     "A delivery may not be raised from a Draft order (it would reserve stock for a commitment "
     "that does not exist yet), nor from a cancelled order, nor from an order whose items never "
     "pass through the warehouse."],
    ["_dlm_check_delivery_allowed()", "Access guard",
     "Only the Storekeeper or Sales may create a delivery document."],
    ["dlm_delivery_state", "Computed · stored",
     "nothing / partial / done — stored so the list view can filter and group on it."],
    ["—", "Cost columns", "Đơn hàng cố ý KHÔNG chép các cột giá vốn từ báo giá."],
]

DCC["dl_sale_order_line"] = [
    ["order_id", "Referential", "NOT NULL, ON DELETE CASCADE."],
    ["line_type", "Enum", "trading / manufactured, default 'trading'."],
    ["quantity", "Range", "Must be strictly greater than 0."],
    ["—", "Copy rule",
     "Chép từ dòng báo giá, BỎ toàn bộ cột chi phí. Vì thế đơn hàng có thể mở cho vai trò không "
     "được xem giá vốn mà không phải lọc từng cột."],
]

# ══════════════════════════════ NHÓM E ═══════════════════════════════════════

DCC["dl.pricing.rule.mixin"] = [
    ["valid_from, valid_to", "Date order",
     "The start of the validity window may not fall after its end."],
    ["company_id", "Required", "NOT NULL, INDEX — every rule is scoped to a company."],
    ["state", "State machine",
     "Technical rules: draft → active → expired. Commercial rules add pending and rejected — see "
     "dl.pricing.commercial.mixin."],
    ["—", "Mixin note",
     "AbstractModel: KHÔNG sinh bảng. Mọi bảng quy tắc giá ở nhóm E đều mang các cột và luật này."],
    ["—", "Lookup rule",
     "Engine chỉ đọc quy tắc có state = 'active' VÀ thời điểm tính nằm trong khoảng hiệu lực. "
     "Đây là lý do state được đánh index ở mọi bảng quy tắc — xem §3.4."],
]

DCC["dl.pricing.commercial.mixin"] = [
    ["state", "State machine",
     "draft → pending → active, plus rejected and expired. Khác với quy tắc KỸ THUẬT, quy tắc "
     "THƯƠNG MẠI bắt buộc đi qua phê duyệt trước khi có hiệu lực."],
    ["—", "Approval coupling",
     "Chuyển sang 'pending' sẽ sinh một dl_pricing_approval_request tương ứng; kết quả duyệt mới "
     "đẩy state sang 'active' hay 'rejected'."],
    ["—", "Separation of duty",
     "Người đề xuất không được tự duyệt đề xuất của mình — xem dl_pricing_approval_matrix."],
]

DCC["dl_pricing_config"] = [
    ["vat_pct", "Range", "Must lie between 0 and 100."],
    ["rounding_to", "Range", "May not be negative; default 1000 ₫."],
    ["name", "Required", "NOT NULL, default “Cấu hình báo giá”."],
    ["—", "Cardinality", "Hệ thống chỉ dùng MỘT dòng cấu hình đang hiệu lực."],
    ["—", "Schema drift",
     "Bảng này hiện có 16 cột mồ côi trên DB đã nâng cấp nhiều lần — bằng chứng cho luật “Odoo "
     "không DROP COLUMN” ở §3.5."],
]

DCC["dl_pricing_complexity_level"] = [
    ["factor", "Range", "Must be strictly greater than 0 — a zero factor would wipe out the cost."],
    ["code", "Uniqueness", "Lookup key of the complexity level."],
    ["—", "Usage", "Hệ số nhân vào chi phí gia công theo độ phức tạp do Kỹ thuật đánh giá."],
]

DCC["dl_pricing_waste_rule"] = [
    ["waste_rate", "Range", "Must lie between 0 and 100 %."],
    ["recovery_rate", "Range",
     "Must lie between 0 and 100 % when has_recovery is on."],
    ["target_type, category_id, product_id", "Conditional required",
     "target_type = 'category' requires a category; target_type = 'product' requires a material. "
     "The rule would otherwise apply to nothing."],
    ["target_type", "Enum required", "category / product, default 'category'."],
    ["state", "State machine", "Inherited from dl.pricing.rule.mixin — draft → active → expired."],
    ["—", "Business meaning",
     "Tỷ lệ hao hụt cộng vào lượng vật tư cần mua; tỷ lệ thu hồi trừ ra phần phế liệu bán lại "
     "được. Kết quả thực tế được đối chiếu hàng tháng ở dl_scrap_recovery_report."],
]

DCC["dl_pricing_operation"] = [
    ["code", "Uniqueness", "DB-level: UNIQUE(code) — “Mã công đoạn phải là duy nhất.”"],
    ["—", "Referential",
     "ON DELETE RESTRICT từ dl_bom_operation_line — không xoá được công đoạn đang có BOM dùng."],
]

DCC["dl_pricing_operation_rule"] = [
    ["price_rate", "Range",
     "For percentage methods the value must lie between 0 and 100 %; for unit methods the unit "
     "price may not be negative."],
    ["setup_fee", "Range", "May not be negative."],
    ["method", "Enum required",
     "percent_material / per_kg / per_meter / per_sqm / per_unit / per_batch, default "
     "'percent_material'. See §3.3."],
    ["state", "State machine", "Inherited from dl.pricing.rule.mixin."],
]

DCC["dl_pricing_cost_adjustment_rule"] = [
    ["value", "Range",
     "Percentage methods: 0–100 %. Factor method: strictly greater than 0. All others: not negative."],
    ["rule_type, condition_days", "Conditional required",
     "An 'urgent' (Giao gấp) charge must declare a maximum lead time greater than 0, otherwise "
     "the rule could never fire."],
    ["rule_type, condition_amount", "Conditional required",
     "A 'small_order' (Đơn hàng nhỏ) charge must declare a maximum order value greater than 0, "
     "for the same reason."],
    ["rule_type", "Enum required",
     "workshop_overhead / packing / shipping / small_order / urgent / complexity / contingency / "
     "other, default 'workshop_overhead'."],
    ["method", "Enum required",
     "percent_direct / percent_cost / per_unit / per_batch / fixed / factor."],
    ["—", "Status note",
     "Bảng đã có dữ liệu và giao diện nhưng CHƯA nối vào engine tính giá ở phiên bản này."],
]

DCC["dl_pricing_profit_rule"] = [
    ["target_markup, min_markup", "Range", "Neither markup may be negative."],
    ["target_markup, min_markup", "Cross-field",
     "The minimum markup may not exceed the target markup — that would make the floor price "
     "higher than the target price."],
    ["state", "State machine",
     "Commercial rule: draft → pending → active, requires approval. See dl.pricing.commercial.mixin."],
    ["—", "Business meaning",
     "Phương pháp “markup trên giá thành”: quyết định giá bán mục tiêu và giá sàn cho mọi báo giá."],
]

DCC["dl_pricing_discount_rule"] = [
    ["default_rate, max_rate", "Range", "Both must lie between 0 and 100 %."],
    ["default_rate, max_rate", "Cross-field",
     "The default discount may not exceed the maximum discount."],
    ["customer_group, default_rate, max_rate", "Monotonic ladder",
     "Chiết khấu phải KHÔNG GIẢM theo bậc gắn bó: khách mới ≤ khách cũ ≤ khách thân thiết. Cấu "
     "hình ngược bậc bị từ chối."],
    ["customer_group", "Enum required", "new / existing / loyal, default 'new'."],
    ["state", "State machine", "Commercial rule — requires approval before it becomes active."],
]

DCC["dl_pricing_approval_matrix"] = [
    ["value_from", "Range", "The threshold may not be negative."],
    ["value_from, state, company_id", "Uniqueness",
     "Only ONE active matrix row per threshold per company; a duplicate threshold is refused."],
    ["value_from, approval_level", "Monotonic ladder",
     "Cấp duyệt phải TĂNG theo giá trị: không thể để ngưỡng cao hơn lại cần cấp duyệt thấp hơn. "
     "Thông điệp nêu đích danh hai ngưỡng đang mâu thuẫn."],
    ["approver_user_id, approval_level", "Cross-field",
     "The named approver must actually belong to the group implied by approval_level, or be left "
     "empty."],
    ["approval_level", "Enum required",
     "none / sales_manager / ceo, default 'sales_manager'. Chỉ lưu ngưỡng ĐẦU; cận trên suy ra "
     "từ dòng kế tiếp."],
    ["write() / unlink()", "CRUD guard",
     "A row with a proposal awaiting the CEO is locked against edit and delete until the proposal "
     "is resolved."],
    ["write()", "Separation of duty",
     "The designated approver of a row may not edit that row's own threshold."],
    ["action_apply()", "Separation of duty",
     "The designated approver may not activate the threshold they themselves approve; another "
     "CEO/Admin must do it."],
    ["action_submit_approval()", "Action guard",
     "Only a draft proposal may be submitted, and only one pending proposal per threshold."],
]

DCC["dl_pricing_approval_setting"] = [
    ["request_type, company_id", "Uniqueness",
     "DB-level: UNIQUE(request_type, company_id) — one approval configuration per request type "
     "per company."],
    ["request_type", "Enum required",
     "profit_config / discount_config / quote_discount / quote_below_floor / "
     "quote_over_threshold / matrix_config."],
    ["approver_role", "Enum required", "sales_manager / ceo, default 'ceo'."],
    ["company_id", "Required", "NOT NULL, INDEX."],
]

DCC["dl_pricing_approval_request"] = [
    ["state", "State machine",
     "pending → approved / rejected / cancelled, default 'pending'. 'cancelled' được đặt tự động "
     "khi báo giá nguồn thay đổi khiến yêu cầu không còn ý nghĩa."],
    ["state", "Indexed", "index=True — hàng đợi phê duyệt luôn lọc theo state."],
    ["request_type", "Enum required", "Same closed list as dl_pricing_approval_setting."],
    ["approval_level", "Enum", "sales_manager / ceo — resolved from the approval matrix."],
    ["company_id", "Required", "NOT NULL, INDEX."],
    ["—", "Separation of duty",
     "Người tạo yêu cầu không được là người duyệt yêu cầu đó."],
    ["—", "Audit", "Kế thừa mail.thread — mọi lần đổi trạng thái để lại vết trong chatter."],
]

DCC["dl_config_audit_log"] = [
    ["user_id", "Default", "env.uid — người đang đăng nhập, không nhập tay."],
    ["create_date", "Immutable", "Cột kiểm toán của Odoo, do ORM đặt."],
    ["—", "Append-only",
     "Không có màn hình sửa hay xoá dòng nhật ký; bảng chỉ ghi thêm."],
]

# ══════════════════════════════ NHÓM F ═══════════════════════════════════════

DCC["stock_warehouse"] = [
    ["—", "Cardinality",
     "Hệ thống giữ ĐÚNG MỘT kho. Tạo kho thứ hai sẽ biến mọi lần chuyển nội bộ thành chuyển "
     "liên kho và phá bố cục 3 khu bên dưới."],
    ["reception_steps", "Invariant",
     "Đặt 'two_steps': NHẬN → KIỂM & CẤT. Đây là điều kiện để có bước kiểm hàng."],
    ["get_rules_dict()", "Override",
     "Chặng 2 của tuyến nhận hàng được ép dùng loại hoạt động “Kiểm & cất hàng” riêng thay vì "
     "chuyển nội bộ chung. Override ở tầng sinh quy tắc — không vá bản ghi stock_rule sau khi "
     "cài — để cấu hình vẫn đúng mỗi lần Odoo dựng lại tuyến."],
    ["code", "Invariant", "'DL' — tiền tố của mọi số phiếu."],
]

DCC["stock_location"] = [
    ["dlm_no_inventory", "Action guard",
     "Kiểm kê tay bị TỪ CHỐI ở tầng máy chủ trên khu quá cảnh (DL/NHAN/QC, DL/NHAN/TRA), không "
     "chỉ ẩn khỏi màn hình: tồn ở đó đang gắn với chứng từ đang mở, đếm tay sẽ xoá mất hàng mà "
     "một phiếu nháp vẫn đang trỏ tới."],
    ["usage", "Invariant",
     "Ba khu để 'internal', KHÔNG để 'view'. _compute_complete_name của Odoo bỏ tiền tố cha với "
     "khu 'view', làm mất “DL/” và lệch với hai khu còn lại."],
    ["location_id", "Structural",
     "FK tự trỏ, ON DELETE CASCADE — cây địa điểm. parent_path là đường dẫn vật chất hoá."],
    ["scrap_location", "Deliberate value",
     "Để FALSE trên DL/XUONG/PL: phế liệu ở Đại Linh là tài sản bán được, không phải hàng huỷ."],
]

DCC["stock_picking_type"] = [
    ["sequence_code", "Enum · discriminator",
     "NH / KC / CK / GH / TR / BPL (+ XSX, NTP dành sẵn cho pha Sản xuất). Đây là khoá mà mã "
     "nghiệp vụ rẽ nhánh theo."],
    ["prefix", "Do not hand-craft",
     "stock.picking.type.write() tự sinh lại prefix theo công thức riêng mỗi lần sequence_code "
     "được ghi — đặt tiền tố tay kiểu “KC/2026/” sẽ bị lặng lẽ ghi đè."],
    ["use_create_lots", "Deliberate value",
     "TRUE trên NH: số lô do Đại Linh tự sinh, không chép từ chứng từ của nhà cung cấp."],
    ["code", "Enum", "incoming / outgoing / internal — Odoo native."],
]

DCC["stock_picking"] = [
    ["picking_type_id", "Discriminator",
     "NOT NULL, INDEX. Một bảng duy nhất đỡ cả sáu loại chứng từ; chuyên biệt hoá bằng QUAN HỆ "
     "chứ không bằng cột phân loại."],
    ["dlm_sale_order_id", "Referential",
     "FK → dl_sale_order, ON DELETE RESTRICT, INDEX — đơn hàng đã có phiếu giao thì không xoá được."],
    ["dlm_origin_picking_id", "Referential",
     "FK tự trỏ, INDEX — lần ngược từ phiếu trả NCC về phiếu kiểm đã sinh ra nó."],
    ["dlm_qc_state", "Computed · stored",
     "none / pending / passed / has_reject — store để danh sách lọc và nhóm được."],
    ["action_confirm()", "Action guard",
     "Xác nhận bị từ chối khi phiếu còn vấn đề; mọi vấn đề được liệt kê một lượt thay vì báo lỗi "
     "từng cái."],
    ["action_dlm_validate_qc()", "Action guard",
     "Xác nhận kiểm bị từ chối nếu còn dòng chưa khai kết quả kiểm."],
    ["_dlm_check_return_decision()", "Access guard",
     "Trả hàng cho nhà cung cấp là quyết định của bộ phận Mua hàng — vai trò khác bị chặn, vì còn "
     "phải thoả thuận đổi hàng hay giảm giá trước khi trả."],
    ["dlm_picking_kind, dlm_banner_level", "Not stored",
     "Selection compute KHÔNG store — suy ra từ picking_type_id mỗi lần đọc, không sinh cột."],
]

DCC["stock_move"] = [
    ["picking_id", "Nullable",
     "CÓ THỂ NULL — một stock_move tồn tại độc lập với phiếu (ví dụ move do kiểm kê sinh ra). "
     "Truy vấn nào giả định luôn có phiếu sẽ sai."],
    ["dlm_qty_rejected", "Range",
     "Không vượt quá số lượng của dòng; phần bị loại đi tiếp vào phiếu trả NCC."],
    ["dlm_reject_reason", "Enum",
     "defect / wrong_spec / wrong_item / other — bắt buộc khi có số lượng bị loại."],
    ["location_id, location_dest_id", "Referential",
     "NOT NULL — mọi dịch chuyển đều có nguồn và đích; đây là cặp cột mà SQL VIEW phế liệu dựa vào."],
    ["state", "Odoo native",
     "draft → waiting → confirmed → assigned → done / cancel. Chỉ move 'done' mới đổi tồn kho."],
]

DCC["stock_move_line"] = [
    ["lot_id", "Conditional required",
     "Bắt buộc khi sản phẩm có theo dõi lô; đây là nơi số lô thực sự được ghi."],
    ["—", "Unchanged",
     "dl_inventory KHÔNG thêm cột nào vào bảng này — dùng nguyên bản Odoo."],
]

DCC["stock_quant"] = [
    ["(product_id, location_id, lot_id)", "Uniqueness",
     "Odoo native — một dòng tồn cho mỗi bộ ba sản phẩm × địa điểm × lô."],
    ["_dlm_check_inventory_allowed()", "Action guard",
     "Kiểm kê tay bị từ chối ở khu quá cảnh — xem stock_location.dlm_no_inventory."],
    ["action_dlm_sell_scrap()", "Action guard",
     "Phải chọn ít nhất một dòng phế liệu CÒN TỒN; và loại hoạt động “Bán phế liệu” phải đã được "
     "cấu hình (chạy -u dl_inventory nếu chưa)."],
    ["dlm_supplier_id, dlm_receipt_date", "Not stored",
     "related tới lot_id — KHÔNG store, nên bảng này không có thêm cột nào từ dl_inventory."],
    ["—", "Derived table",
     "Odoo tự duy trì tồn từ các move đã 'done'; không sửa tay ngoài đường kiểm kê."],
]

DCC["stock_lot"] = [
    ["name", "Uniqueness",
     "Duy nhất theo sản phẩm. Sinh theo định dạng LO/2026/00001 bằng ir.sequence — Đại Linh tự "
     "đánh số lô thay vì chép số của nhà cung cấp."],
    ["dlm_supplier_id", "Referential",
     "FK → res_partner, INDEX — truy ngược hàng lỗi về đúng nhà cung cấp đã giao."],
    ["dlm_receipt_date", "Indexed", "index=True — báo cáo tuổi tồn lọc theo ngày nhập."],
    ["action_dlm_open_receipt()", "Action guard",
     "Từ chối khi lô chưa gắn phiếu nhận nào."],
    ["dlm_receipt_picking_id", "Referential", "FK → stock_picking — phiếu nhận đã sinh ra lô."],
]

DCC["procurement_group"] = [
    ["—", "Unchanged", "Dùng nguyên bản; dl_inventory không thêm cột."],
    ["—", "Purpose",
     "Gắn hai chặng của tuyến nhận hàng hai bước vào cùng một lần giao, để hệ thống biết chúng "
     "thuộc cùng một chuyến hàng."],
]

DCC["dl_scrap_recovery_report"] = [
    ["—", "Not a table",
     "_auto = False ⇒ đây là CREATE OR REPLACE VIEW. Không có sequence khoá chính, không có cột "
     "kiểm toán, KHÔNG có đường INSERT/UPDATE/DELETE."],
    ["qty_estimated, qty_diff, diff_level", "Not in the view",
     "Ba giá trị này là compute Python, KHÔNG nằm trong SQL VIEW. Đưa chúng vào hộp ERD là mô tả "
     "sai tầng vật lý."],
    ["diff_level", "Enum", "short / match / over — xem §3.3."],
    ["period", "Grouping key",
     "View là UNION của “tháng có phát sinh phế liệu” và “tháng có đơn bán hàng”. Nếu chỉ lấy "
     "tháng có phát sinh thì tháng bán nhiều mà không thu hồi được sẽ biến mất khỏi báo cáo — "
     "đúng lúc cần nhìn thấy nhất."],
    ["—", "Read-only",
     "Mọi ràng buộc toàn vẹn nằm ở các bảng nguồn (stock_move, stock_location, dl_sale_order); "
     "view không tự áp ràng buộc nào."],
]
