# -*- coding: utf-8 -*-
"""§3.2 Entity Relationships + phần bổ sung cho §3.3 / §3.4 / §3.6."""
import json
import os

D = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '.tmp_erd')

# ───────────────────────── 3.2 Entity Relationships ──────────────────────────

REL_LEAD = (
    "The physical model contains 35 custom storage tables, 1 SQL view, 2 many-to-many link "
    "tables, 9 Odoo core tables extended with dlm_ columns and 9 further core tables referenced "
    "by foreign key. Drawing all of them with full column lists on one canvas would require "
    "roughly 9 000 × 6 000 px and print unreadably at A4, so the diagram is split into one "
    "overview plus six subject-area diagrams."
)

DIAG_LEAD = (
    "The six subject areas use the same names and the same boundaries as the pages of the "
    "conceptual ERD, so a conceptual entity and its physical table can be located side by side."
)

DIAG_HEADERS = ["Diagram", "Scope", "Tables"]
DIAG_WIDTHS = [22, 48, 14]
DIAG_ROWS = [
    ["0 — Overview / Table map",
     "Every table, showing table name and primary key only, grouped by module, with all foreign "
     "keys. This is the “whole database in one picture” view.", "56"],
    ["A — Partners, Users, RBAC",
     "res_partner, res_users, res_company, res_country, dl_rbac_feature, dl_rbac_operation", "6"],
    ["B — Product & Material catalogue",
     "product_product, product_template, product_category, product_supplierinfo, uom_uom, "
     "dl_measurement_type, dl_measurement_shape, dl_measurement_shape_param", "8"],
    ["C — Engineering: drawings, BOM, RFQ",
     "dl_drawing, dl_bom, dl_bom_line, dl_bom_operation_line, dl_bom_template(+line, +param, "
     "+param_map), dl_quotation_request(+line, +line_image) and the 2 m2m link tables", "13"],
    ["D — Sales: quotations & orders",
     "dl_quotation, dl_quotation_line, dl_quotation_price_component, dl_sale_order, "
     "dl_sale_order_line", "5"],
    ["E — Pricing configuration & approval",
     "dl_pricing_config, dl_pricing_complexity_level, the 6 rule tables, "
     "dl_pricing_approval_matrix/_setting/_request, dl_config_audit_log", "14"],
    ["F — Inventory",
     "stock_warehouse, stock_location, stock_picking_type, stock_picking, stock_move, "
     "stock_move_line, stock_quant, stock_lot, procurement_group, dl_scrap_recovery_report", "10"],
]

DIAG_NOTE_LABEL = "Why six diagrams rather than one, and how cross-diagram edges are handled"
DIAG_NOTE = (
    "Of the 64 foreign keys that cross a subject-area boundary, 47 (73 %) point at just five hub "
    "tables: res_partner, res_users, res_company, product_product and product_category. Those five "
    "are repeated on every diagram that needs them as a reference box — grey fill, primary key "
    "only, labelled with the diagram that owns them. That leaves 17 genuinely cross-domain edges, "
    "which are annotated individually. Core tables with very wide row definitions (res_partner 58 "
    "columns, stock_move 45, stock_picking_type 42) are drawn in reduced form: primary key, the "
    "foreign keys actually used, and every dlm_ column, with a “+ N further core columns” footer."
)

CONV_HEADERS = ["Notation", "Meaning"]
CONV_WIDTHS = [26, 74]
CONV_ROWS = [
    ["Solid box, bold title", "Custom table created by this project (dl_*)"],
    ["Solid box, light fill", "Odoo core table extended with dlm_ columns — the extended columns are shown in full"],
    ["Grey box", "Odoo core table used unchanged, or a hub table repeated from another diagram"],
    ["Dashed box", "PostgreSQL VIEW (_auto = False) — read-only, no INSERT/UPDATE path"],
    ["Small rounded box", "Many-to-many link table generated by the ORM"],
    ["Crow's foot", "Cardinality. A circle on the parent side marks an OPTIONAL parent (nullable foreign key)"],
    ["Edge label", "ON DELETE policy: RESTRICT, SET NULL or CASCADE"],
]

REL_TBL_LEAD = (
    "Every foreign key of the model is listed below, grouped by subject area. The audit columns "
    "create_uid and write_uid are present on every table (both → res_users, ON DELETE SET NULL) "
    "and are omitted from this list to keep it readable. Transient (wizard) tables are excluded — "
    "see the note at the end of §3.1."
)

REL_HEADERS = ["Child table", "Foreign key column", "Parent table", "ON DELETE", "Null"]
REL_WIDTHS = [27, 26, 25, 13, 9]

# FK do Odoo core khai báo trên nhóm Kho — không có trong source dl_*, bổ sung tay
CORE_STOCK_FK = [
    ("stock_location", "location_id", "stock_location", "CASCADE", "NULL"),
    ("stock_location", "warehouse_id", "stock_warehouse", "SET NULL", "NULL"),
    ("stock_location", "company_id", "res_company", "SET NULL", "NULL"),
    ("stock_picking_type", "warehouse_id", "stock_warehouse", "CASCADE", "NULL"),
    ("stock_picking_type", "sequence_id", "ir_sequence", "SET NULL", "NULL"),
    ("stock_picking_type", "default_location_src_id", "stock_location", "SET NULL", "NULL"),
    ("stock_picking_type", "default_location_dest_id", "stock_location", "SET NULL", "NULL"),
    ("stock_picking_type", "return_picking_type_id", "stock_picking_type", "SET NULL", "NULL"),
    ("stock_picking_type", "company_id", "res_company", "RESTRICT", "NOT NULL"),
    ("stock_picking", "picking_type_id", "stock_picking_type", "RESTRICT", "NOT NULL"),
    ("stock_picking", "location_id", "stock_location", "RESTRICT", "NOT NULL"),
    ("stock_picking", "location_dest_id", "stock_location", "RESTRICT", "NOT NULL"),
    ("stock_picking", "partner_id", "res_partner", "SET NULL", "NULL"),
    ("stock_picking", "backorder_id", "stock_picking", "SET NULL", "NULL"),
    ("stock_picking", "group_id", "procurement_group", "SET NULL", "NULL"),
    ("stock_picking", "user_id", "res_users", "SET NULL", "NULL"),
    ("stock_picking", "company_id", "res_company", "SET NULL", "NULL"),
    ("stock_move", "picking_id", "stock_picking", "SET NULL", "NULL"),
    ("stock_move", "product_id", "product_product", "RESTRICT", "NOT NULL"),
    ("stock_move", "product_uom", "uom_uom", "RESTRICT", "NOT NULL"),
    ("stock_move", "location_id", "stock_location", "RESTRICT", "NOT NULL"),
    ("stock_move", "location_dest_id", "stock_location", "RESTRICT", "NOT NULL"),
    ("stock_move", "picking_type_id", "stock_picking_type", "SET NULL", "NULL"),
    ("stock_move", "group_id", "procurement_group", "SET NULL", "NULL"),
    ("stock_move", "origin_returned_move_id", "stock_move", "SET NULL", "NULL"),
    ("stock_move", "company_id", "res_company", "RESTRICT", "NOT NULL"),
    ("stock_move_line", "move_id", "stock_move", "SET NULL", "NULL"),
    ("stock_move_line", "picking_id", "stock_picking", "SET NULL", "NULL"),
    ("stock_move_line", "product_id", "product_product", "CASCADE", "NULL"),
    ("stock_move_line", "lot_id", "stock_lot", "SET NULL", "NULL"),
    ("stock_move_line", "location_id", "stock_location", "RESTRICT", "NOT NULL"),
    ("stock_move_line", "location_dest_id", "stock_location", "RESTRICT", "NOT NULL"),
    ("stock_move_line", "company_id", "res_company", "RESTRICT", "NOT NULL"),
    ("stock_quant", "product_id", "product_product", "RESTRICT", "NOT NULL"),
    ("stock_quant", "location_id", "stock_location", "RESTRICT", "NOT NULL"),
    ("stock_quant", "lot_id", "stock_lot", "RESTRICT", "NULL"),
    ("stock_quant", "company_id", "res_company", "SET NULL", "NULL"),
    ("stock_lot", "product_id", "product_product", "RESTRICT", "NOT NULL"),
    ("stock_lot", "product_uom_id", "uom_uom", "SET NULL", "NULL"),
    ("stock_lot", "location_id", "stock_location", "SET NULL", "NULL"),
    ("stock_lot", "company_id", "res_company", "RESTRICT", "NOT NULL"),
    ("procurement_group", "partner_id", "res_partner", "SET NULL", "NULL"),
]

M2M_FK = [
    ("dl_rfq_line_ir_attachment_rel", "line_id", "dl_quotation_request_line", "CASCADE", "NOT NULL"),
    ("dl_rfq_line_ir_attachment_rel", "attachment_id", "ir_attachment", "CASCADE", "NOT NULL"),
    ("dl_bom_line_dl_bom_operation_line_rel", "dl_bom_line_id", "dl_bom_line", "CASCADE", "NOT NULL"),
    ("dl_bom_line_dl_bom_operation_line_rel", "dl_bom_operation_line_id", "dl_bom_operation_line", "CASCADE", "NOT NULL"),
]

GROUP_OF = {}
for t in ('res_partner', 'res_users', 'res_company', 'res_country',
          'dl_rbac_feature', 'dl_rbac_operation'):
    GROUP_OF[t] = 'A'
for t in ('product_product', 'product_template', 'product_category',
          'product_supplierinfo', 'uom_uom', 'dl_measurement_type',
          'dl_measurement_shape', 'dl_measurement_shape_param'):
    GROUP_OF[t] = 'B'
for t in ('dl_drawing', 'dl_bom', 'dl_bom_line', 'dl_bom_operation_line', 'dl_bom_template',
          'dl_bom_template_line', 'dl_bom_template_param', 'dl_bom_template_line_param_map',
          'dl_quotation_request', 'dl_quotation_request_line', 'dl_quotation_request_line_image',
          'dl_rfq_line_ir_attachment_rel', 'dl_bom_line_dl_bom_operation_line_rel'):
    GROUP_OF[t] = 'C'
for t in ('dl_quotation', 'dl_quotation_line', 'dl_quotation_price_component',
          'dl_sale_order', 'dl_sale_order_line'):
    GROUP_OF[t] = 'D'
for t in ('dl_pricing_config', 'dl_pricing_complexity_level', 'dl_pricing_waste_rule',
          'dl_pricing_operation', 'dl_pricing_operation_rule', 'dl_pricing_cost_adjustment_rule',
          'dl_pricing_profit_rule', 'dl_pricing_discount_rule', 'dl_pricing_approval_matrix',
          'dl_pricing_approval_setting', 'dl_pricing_approval_request', 'dl_config_audit_log',
          'dl_pricing_waste', 'dl_approval_level'):
    GROUP_OF[t] = 'E'
for t in ('stock_warehouse', 'stock_location', 'stock_picking_type', 'stock_picking',
          'stock_move', 'stock_move_line', 'stock_quant', 'stock_lot', 'procurement_group',
          'dl_scrap_recovery_report'):
    GROUP_OF[t] = 'F'

GROUP_TITLE = {
    'A': 'A — Partners, Users, RBAC',
    'B': 'B — Product & Material catalogue',
    'C': 'C — Engineering: drawings, BOM, RFQ',
    'D': 'D — Sales: quotations & orders',
    'E': 'E — Pricing configuration & approval',
    'F': 'F — Inventory',
}


def build_rel_rows():
    """Trả về list row + dòng GROUP, gom theo nhóm chủ đề của BẢNG CON."""
    src = json.load(open(os.path.join(D, 'rel_rows.json'), encoding='utf-8'))
    buckets = {k: [] for k in GROUP_TITLE}
    for child, col, parent, card, ondel, nullable, idx in src:
        g = GROUP_OF.get(child)
        if g:
            buckets[g].append([child, col, parent, ondel, nullable])
    for child, col, parent, ondel, nullable in CORE_STOCK_FK:
        buckets['F'].append([child, col, parent, ondel, nullable])
    for child, col, parent, ondel, nullable in M2M_FK:
        buckets['C'].append([child, col, parent, ondel, nullable])

    out = []
    total = 0
    for g in ('A', 'B', 'C', 'D', 'E', 'F'):
        rows = sorted(buckets[g], key=lambda r: (r[0], r[1]))
        if not rows:
            continue
        out.append(('GROUP', '%s   —   %d foreign keys' % (GROUP_TITLE[g], len(rows))))
        out.extend(rows)
        total += len(rows)
    return out, total


REL_NOTE_LABEL = "Two structural facts the diagram must show correctly"
REL_NOTE = (
    "(1) stock_picking → stock_move is OPTIONAL-to-many. Inventory adjustment lines are created "
    "with is_inventory = TRUE and no parent picking, so picking_id is nullable. "
    "(2) The six kinds of warehouse document are NOT six tables and NOT six subtypes with their "
    "own columns — they share one table and are discriminated by picking_type_id, which is itself "
    "an entity. Specialisation here is defined by a relationship, not by a type column."
)

# ─────────────────────────── 3.3 Enum — bổ sung Kho ──────────────────────────

ENUM_KHO_ROWS = [
    ["stock_picking", "dlm_qc_state",
     "none / pending / passed / has_reject",
     "Inspection outcome. Computed and STORED so the list view can group on it. none = the "
     "document is not an inspection document"],
    ["stock_picking", "dlm_picking_kind",
     "receipt / qc / transfer / delivery / vendor_return / scrap_sale / other",
     "Document kind, derived from picking_type_id.sequence_code. NOT stored — display and routing "
     "only"],
    ["stock_picking", "dlm_banner_level",
     "info / success / warning / danger",
     "Severity of the inline banner on the form. NOT stored"],
    ["stock_move", "dlm_reject_reason",
     "defect / wrong_spec / wrong_item / other",
     "Why the quantity failed inspection: damaged goods / wrong specification / wrong item "
     "delivered / other"],
    ["dl_sale_order", "dlm_delivery_state",
     "nothing / partial / done",
     "Delivery status of the order. Computed and STORED, default nothing"],
    ["dl_scrap_recovery_report", "diff_level",
     "short / match / over",
     "short = less scrap recovered than estimated, i.e. the real cost of goods is HIGHER than the "
     "price quoted to the customer. Computed in Python, not part of the SQL view"],
    ["stock_location", "usage [Native]",
     "view / internal / supplier / customer / production / inventory",
     "Odoo core. The scrap SQL view uses usage = 'customer' to recognise a scrap sale"],
    ["stock_picking_type", "code [Native]",
     "incoming / outgoing / internal",
     "Odoo core. Combined with sequence_code (NH / KC / CK / GH / TR / BPL / XSX / NTP) it defines "
     "the 8 operation types"],
]

# ────────────────────────── 3.4 Indexing — bổ sung Kho ───────────────────────

IDX_KHO_ROWS = [
    ["stock_picking", "dlm_sale_order_id", "BTREE", "index=True",
     "Open a sales order and list its delivery documents"],
    ["stock_picking", "dlm_origin_picking_id", "BTREE", "index=True",
     "Trace a vendor return back to the inspection document that produced it"],
    ["stock_lot", "dlm_supplier_id", "BTREE", "index=True",
     "Trace defective goods back to the supplying vendor"],
    ["stock_lot", "dlm_receipt_date", "BTREE", "index=True",
     "Stock ageing reports filter on receipt date"],
]

IDX_KHO_NOTE_LABEL = "Indexes deliberately NOT created for the inventory module"
IDX_KHO_NOTE = (
    "dlm_qc_state and dlm_qty_rejected_total are stored but not indexed. Both are only ever read "
    "after the query has already been narrowed by picking_type_id — which Odoo indexes as a "
    "many-to-one used in the domain — so an additional index would be maintained on every write "
    "and used by no query. dl_scrap_recovery_report cannot be indexed at all: it is a view, and "
    "its selectivity comes from the indexes on stock_move.date and stock_location.parent_path."
)

# ─────────────────────────── 3.6 Seed Data — bổ sung ─────────────────────────

SEED_ACCOUNT_ROW = ["Thủ kho", "dl_group_warehouse",
                    "Test receiving, inspection, put-away, delivery, vendor return and scrap "
                    "sale; read-only on sales orders"]

SEED_KHO_ROWS = [
    ["stock.warehouse", "1", "The single warehouse DL — renamed from Odoo's stock.warehouse0, "
                             "reception_steps = two_steps"],
    ["stock.location", "7", "DL/NHAN (+QC, +KHO, +TRA) · DL/XUONG (+BTP, +PL) · DL/TP — three "
                            "zones, all usage = internal"],
    ["stock.picking.type", "8", "NH · KC · CK · GH · TR · BPL seeded for phase 1; XSX · NTP "
                                "seeded ahead for the Manufacturing phase"],
    ["ir.sequence (lot)", "1", "Prefix LO/%(year)s/, padding 5 — Đại Linh generates its own lot "
                               "numbers"],
    ["stock.picking — receipt", "2", "1 × done (creates a lot with dlm_supplier_id set); "
                                     "1 × assigned awaiting inspection"],
    ["stock.picking — inspection", "1", "dlm_qc_state = has_reject, with one line carrying "
                                        "dlm_qty_rejected > 0 and dlm_reject_reason = wrong_spec"],
    ["stock.picking — delivery", "1", "Linked to a confirmed dl.sale.order so that "
                                      "dlm_delivery_state becomes partial"],
    ["stock.move (scrap)", "2", "1 × into DL/XUONG/PL, 1 × out to a customer location — the "
                                "minimum needed for dl_scrap_recovery_report to return a non-empty "
                                "row"],
]

SEED_NOTE_LABEL = "Seed data must be loaded on a clean database"
SEED_NOTE = (
    "The warehouse layout is seeded by a <function> call, not by <record> elements: the records it "
    "has to modify (stock.warehouse0, the Input and Stock locations, the three native operation "
    "types) are flagged noupdate=\"True\", so <record> would be silently ignored. The seed function "
    "is idempotent — re-running odoo-bin -u dl_inventory does not duplicate anything."
)
