{
    'name': 'DLM-ERP Quản lý Nhà cung cấp Vật tư',
    'version': '17.0.3.0.0',
    'summary': 'Danh mục NCC/Thầu phụ (theo TDS 4.0 — dl.partner, không bảng riêng)',
    'author': 'Dai Linh',
    'category': 'Hidden',
    'depends': ['dl_base', 'dl_sale', 'dlm_material', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/rbac_features.xml',
        'data/res_partner_category_data.xml',
        'views/res_partner_views.xml',
        'views/dl_material_views.xml',
        'views/material_price_views.xml',
        'data/ir_sequence_data.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
