# -*- coding: utf-8 -*-
# UC-ID -> (Description, BF-ID, Relationship)
# BF-ID: chỉ điền khi có bằng chứng từ bảng FT (map UC->FT->BF); để trống nếu không rõ
# (tài liệu gốc không còn giữ phần định nghĩa Business Flow sau khi bạn cắt bớt).

UC_DATA = {
    # --- AUTH ---
    "UC-001": ("Người dùng đăng nhập bằng email và mật khẩu đã được Admin cấp.", "", ""),
    "UC-002": ("Thanh điều hướng giúp di chuyển giữa các phần của hệ thống sau khi đăng nhập.", "BF-07", ""),
    "UC-003": ("Admin xem ma trận quyền của từng vai trò trên toàn bộ chức năng hệ thống.", "BF-06", "Liên quan UC-005"),
    "UC-004": ("Admin tạo, đổi tên hoặc xoá vai trò tự tạo (vai trò cài sẵn theo module không xoá được).", "BF-06", "Liên quan UC-092 (FT-92 bảo vệ vai trò hệ thống)"),
    "UC-005": ("Admin bật/tắt quyền Xem-Thêm-Sửa-Xóa và các thao tác đặc biệt cho từng vai trò, ghi thẳng vào hệ quyền thật.", "BF-06", "Liên quan UC-003, UC-004"),
    "UC-006": ("Admin xem danh sách người dùng, tìm kiếm và lọc theo vai trò/trạng thái.", "BF-06", "Tiền đề của UC-007, UC-008"),
    "UC-007": ("Admin tạo tài khoản người dùng mới, hệ thống tự gửi email mời đặt mật khẩu.", "BF-06", ""),
    "UC-008": ("Admin gán vai trò, đặt lại mật khẩu hoặc khoá/mở lại một tài khoản người dùng.", "BF-06", ""),
    "UC-009": ("Admin chỉ định người duyệt dự phòng (Backup Approver) cho một người dùng khi người đó vắng mặt.", "BF-04, BF-06", "Liên quan UC-025"),
    "UC-010": ("CEO xem (chỉ đọc), Kỹ thuật và Kế toán nội bộ cấu hình tỷ lệ hao hụt/thu hồi phế liệu mặc định theo nhóm vật tư hoặc từng vật tư.", "BF-06", "Tự điền vào UC-044, UC-058 khi lập định mức"),
    "UC-011": ("CEO đặt các mốc giá trị báo giá và cấp duyệt tương ứng, mỗi lần đổi lưu thành phiên bản mới.", "BF-06", "Liên quan UC-023, UC-024"),
    "UC-012": ("Cấu hình thời hạn xử lý (SLA) và cơ chế nhắc/chuyển việc khi quá hạn — chưa triển khai.", "", ""),
    "UC-013": ("Tra cứu ai đã đổi cấu hình nào, vào lúc nào — hiện chỉ ghi log riêng cho VAT/mức làm tròn, các quy tắc khác dùng lịch sử thay đổi (chatter) trên từng bản ghi, chưa có màn tra cứu tổng hợp.", "BF-06", ""),
    "UC-014": ("Admin/CEO khai báo và quản lý các đơn vị đo dùng chung (kg, mét, cái...).", "BF-06", ""),
    "UC-015": ("Mở màn Cấu hình Báo giá — một màn nhiều tab (hao hụt, công đoạn, chi phí chung, lợi nhuận & chiết khấu, phê duyệt, danh mục), mỗi vai trò chỉ thấy nút phù hợp với quyền của mình.", "BF-06", "Là cửa vào chung cho UC-010, UC-011, UC-016, UC-020, UC-021, UC-023, UC-024, UC-025, UC-037"),
    "UC-016": ("Kỹ thuật và Kế toán nội bộ tạo/sửa quy tắc kỹ thuật: hao hụt, công đoạn gia công, chi phí chung.", "BF-06", "Dùng khi lập định mức UC-058, UC-065"),
    "UC-017": ("Kỹ thuật và Kế toán nội bộ quản lý danh mục dùng chung: công đoạn, mức độ phức tạp.", "BF-06", "Dùng bởi UC-066 (khai báo công đoạn trên BOM)"),
    "UC-018": ("Kỹ thuật và Kế toán nội bộ áp dụng hoặc ngừng áp dụng một quy tắc kỹ thuật.", "BF-06", ""),
    "UC-019": ("Kỹ thuật tạo bản sửa đổi (revision) mới cho một quy tắc kỹ thuật, giữ lại lịch sử các bản trước.", "BF-06", ""),
    "UC-020": ("CEO tạo chính sách lợi nhuận mục tiêu và giá sàn, phải qua phê duyệt trước khi áp dụng.", "BF-06", "Là input cho UC-078 (tính giá báo giá)"),
    "UC-021": ("Trưởng phòng Kinh doanh tạo chính sách chiết khấu theo từng nhóm khách hàng (mới/cũ/thân thiết).", "BF-06", "Là input cho UC-080"),
    "UC-022": ("CEO/Trưởng phòng Kinh doanh gửi duyệt một thay đổi cấu hình thương mại (lợi nhuận, chiết khấu).", "BF-04, BF-06", "Sinh ra UC-026"),
    "UC-023": ("Trưởng phòng Kinh doanh đề xuất các mốc ngưỡng giá trị cần phê duyệt báo giá.", "BF-06", "Chờ CEO áp dụng ở UC-024"),
    "UC-024": ("CEO áp dụng ngưỡng phê duyệt báo giá theo giá trị đã được đề xuất.", "BF-06", "Là input cho UC-081 (định tuyến phê duyệt)"),
    "UC-025": ("CEO chỉ định người duyệt cho từng loại yêu cầu phê duyệt.", "BF-04, BF-06", "Liên quan UC-009 (người duyệt dự phòng)"),
    "UC-026": ("CEO duyệt hoặc từ chối một yêu cầu thay đổi cấu hình thương mại.", "BF-04, BF-06", ""),
    "UC-027": ("Xem danh sách các yêu cầu phê duyệt cấu hình đang chờ hoặc đã xử lý.", "BF-04", "Tiền đề của UC-026"),
    # --- BPM ---
    "UC-028": ("Nhân viên Kinh doanh tạo/sửa/xem hồ sơ khách hàng: liên hệ, địa chỉ, mã số thuế, loại khách hàng.", "", "Sinh mã khách hàng tự động (KH-0001)"),
    "UC-029": ("Khi một đối tác vừa mua vừa bán, liên kết hồ sơ khách hàng và nhà cung cấp thành một bản ghi dùng chung — chỉ thực hiện được lúc tạo mới.", "", ""),
    "UC-030": ("Vô hiệu hoá một khách hàng để ngừng hợp tác (giữ nguyên dữ liệu cũ) và kích hoạt lại khi cần.", "", ""),
    "UC-031": ("Tra cứu, lọc và nhóm danh sách khách hàng theo loại, nhóm, trạng thái, nhãn.", "", ""),
    "UC-032": ("Trưởng phòng Kinh doanh gắn nhãn tự do (VD: Khách quen, VIP) cho khách hàng/NCC để lọc nhanh.", "", ""),
    "UC-033": ("Quản lý hồ sơ nhà cung cấp/thầu phụ: thông tin liên hệ, địa chỉ, mã số thuế.", "", ""),
    "UC-034": ("Trưởng phòng Kinh doanh/Kế toán nội bộ xem danh sách nhà cung cấp ở chế độ chỉ đọc.", "", ""),
    "UC-035": ("Xem số báo giá, tỷ lệ thắng, số báo giá chưa đóng và các cảnh báo (KH ngừng hợp tác còn báo giá mở, cảnh báo gộp đơn né duyệt) ngay trên hồ sơ khách hàng.", "", "Logic đặt ở module Bán hàng"),
    "UC-036": ("Hệ thống tự xếp khách hàng vào nhóm Khách mới/Khách cũ/Khách thân thiết dựa trên lịch sử báo giá đã chốt, tính lại ngay khi báo giá đổi trạng thái.", "", "Dùng ngưỡng cấu hình ở UC-037"),
    "UC-037": ("Admin/CEO cấu hình mức doanh số để khách hàng tự được xếp vào nhóm Thân thiết.", "BF-06", "Input cho UC-036"),
    # --- PROD ---
    "UC-038": ("Kỹ thuật và Trưởng phòng Kinh doanh quản lý các nhóm dùng để phân loại sản phẩm và vật tư.", "BF-02", ""),
    "UC-039": ("Kỹ thuật tạo sản phẩm gia công (sản phẩm đặt làm theo yêu cầu khách).", "BF-02", ""),
    "UC-040": ("Nhân viên Kinh doanh tạo sản phẩm thương mại (hàng mua sẵn để bán lại).", "BF-02", "Cần đủ giá mua/bán mới kích hoạt được — UC-045"),
    "UC-041": ("Nhân viên Kinh doanh đặt giá bán cho sản phẩm thương mại và xem mức lợi nhuận so với giá vốn.", "BF-02", ""),
    "UC-042": ("Kỹ thuật tạo vật tư dùng để lập định mức.", "BF-02", ""),
    "UC-043": ("Kỹ thuật tạo bán thành phẩm (sản phẩm trung gian dùng trong định mức của sản phẩm khác).", "BF-02", ""),
    "UC-044": ("Kỹ thuật khai báo tỷ lệ hao hụt cơ sở khi gia công và phần phế liệu thu hồi được của từng vật tư.", "BF-02, BF-06", "Dùng bởi UC-058, UC-092C"),
    "UC-045": ("Chuyển vòng đời sản phẩm giữa 3 trạng thái Nháp/Đã duyệt/Ngừng sử dụng; sản phẩm thương mại chỉ kích hoạt được khi đủ giá mua/bán hợp lệ.", "BF-02", "Tự động hoá một phần ở UC-046, UC-047"),
    "UC-045A": ("Chặn thao tác kích hoạt tay đối với sản phẩm/BOM còn ở trạng thái tạm sinh ra trong lúc xử lý RFQ (`is_rfq_provisional`), tránh dùng nhầm dữ liệu chưa chính thức hoá.", "BF-02", "Bảo vệ cho UC-068, UC-069"),
    "UC-046": ("Khi đơn bán hàng được xác nhận, hệ thống tự chuẩn hoá tên/mã và nâng cấp sản phẩm gia công liên quan từ Nháp lên Đã duyệt.", "BF-02", "Kích hoạt bởi UC-089"),
    "UC-047": ("Mỗi ngày hệ thống tự động chuyển sản phẩm/bán thành phẩm Nháp không dùng trong đơn hàng nào sau một số ngày cấu hình được sang Ngừng sử dụng.", "BF-02", "Xem JOB-03"),
    "UC-048": ("Kỹ thuật rà soát danh sách sản phẩm nháp chưa dùng để tự tay ngừng sử dụng sớm hơn lịch tự động.", "BF-02", "Liên quan UC-047"),
    "UC-049": ("Kế toán nội bộ / Mua hàng tạo bảng giá của một nhà cung cấp cho một vật tư.", "", ""),
    "UC-050": ("Quản lý vòng đời bảng giá nhà cung cấp: Nháp → Đã duyệt → Đang áp dụng.", "", "Kích hoạt UC-113 khi áp dụng"),
    "UC-051": ("Admin cấu hình đơn vị đo dùng chung; cách tính định mức theo quy cách vật tư (cắt chiều dài/cắt tấm/đếm chiếc/khối lượng rời) khai trực tiếp trên từng vật tư.", "BF-02", "Input cho UC-058"),
    "UC-052": ("CEO/Trưởng phòng Kinh doanh tra cứu danh mục sản phẩm, vật tư.", "BF-02", ""),
    # --- TECH ---
    "UC-053": ("Kỹ thuật tạo bản vẽ kỹ thuật gắn với một sản phẩm gia công/bán thành phẩm.", "BF-02", ""),
    "UC-054": ("Kỹ thuật chuyển trạng thái bản vẽ: Nháp → Đã xác nhận → Lưu trữ; xác nhận bản vẽ mới sẽ nhắc các BOM liên quan rà lại định mức.", "BF-02", ""),
    "UC-055": ("Tải lên và xem bản vẽ kỹ thuật ngay trên màn BOM, không cần mở màn Bản vẽ riêng.", "BF-02", ""),
    "UC-056": ("Kỹ thuật tạo định mức (BOM) cho một sản phẩm hoặc bán thành phẩm.", "BF-02", ""),
    "UC-057": ("Kỹ thuật thêm dòng vật tư vào BOM, hệ thống tự tính số lượng cần dùng theo kích thước với vật tư dạng cắt chiều dài/cắt tấm.", "BF-02", "Dùng công thức ở UC-058"),
    "UC-057A": ("Kỹ thuật thêm một bán thành phẩm vào định mức; hệ thống tự cộng gộp vật tư từ định mức của bán thành phẩm đó (BOM nhiều cấp).", "BF-02", ""),
    "UC-058": ("Hệ thống tự tính số lượng vật tư cần dùng từ kích thước nhập vào dòng BOM, theo 2 kiểu: cắt theo chiều dài (1D) hoặc cắt tấm (2D); chưa hỗ trợ hình dạng phức tạp hơn.", "BF-02", "Dùng bởi UC-057"),
    "UC-059": ("Kỹ thuật ghi đè tay số lượng định mức đã tự tính, kèm lý do.", "BF-02", ""),
    "UC-060": ("Kỹ thuật chuyển trạng thái BOM: Nháp → Đã xác nhận → Đã khoá (và Lưu trữ).", "BF-02", ""),
    "UC-060A": ("Khi một phiên bản BOM chuẩn mới được xác nhận, hệ thống tự đánh dấu nó là phiên bản hiện hành, bỏ cờ phiên bản cũ (chỉ áp dụng cho BOM chuẩn, không áp dụng cho BOM sinh riêng theo báo giá).", "BF-02", ""),
    "UC-061": ("Kỹ thuật tạo phiên bản BOM mới từ một BOM chuẩn đã có.", "BF-02", "Kích hoạt UC-060A"),
    "UC-062": ("Kỹ thuật tạo nhanh một BOM mới từ BOM mẫu có sẵn (sao chép dòng tĩnh, hoặc sinh theo tham số nếu là mẫu có tham số).", "BF-02", "Liên quan UC-063, UC-063A, UC-069A"),
    "UC-063": ("Kỹ thuật quản lý các BOM mẫu dùng để tạo nhanh định mức mới cho một nhóm sản phẩm.", "BF-02", ""),
    "UC-063A": ("Kỹ thuật khai báo tham số (mã, khoảng giá trị hợp lệ) và ánh xạ tuyến tính từ tham số vào kích thước từng dòng của BOM mẫu.", "BF-02", "Dùng bởi UC-069A"),
    "UC-064": ("Nhân viên Kinh doanh tạo yêu cầu báo giá (RFQ) mới từ nhu cầu khách hàng.", "", "Mở đầu luồng RFQ → UC-078"),
    "UC-065": ("Hệ thống tự động đánh dấu một RFQ mới tạo ở trạng thái đã tiếp nhận, sẵn sàng cho Kỹ thuật xử lý.", "", ""),
    "UC-066": ("Kỹ thuật mở workspace xử lý từng dòng RFQ: xác định sản phẩm, lập định mức, xác nhận kết quả.", "", "Cửa vào chung cho UC-067 đến UC-072"),
    "UC-067": ("Kỹ thuật chọn một sản phẩm có sẵn cho dòng RFQ; hệ thống tự gợi ý sản phẩm đã từng gia công tương tự dựa trên tên, nhóm, khách hàng, kích thước.", "", ""),
    "UC-068": ("Kỹ thuật tạo sản phẩm mới ngay trong màn xử lý RFQ khi chưa có sản phẩm phù hợp; hệ thống cảnh báo nếu trùng/gần giống tên.", "BF-02", ""),
    "UC-069": ("Kỹ thuật tạo BOM mới ngay trong màn xử lý RFQ.", "BF-02", ""),
    "UC-069A": ("Kỹ thuật sinh định mức từ BOM mẫu tham số bằng cách nhập giá trị tham số (kích thước); tái sử dụng BOM cũ nếu đã từng sinh đúng bộ tham số này.", "BF-02", ""),
    "UC-070": ("Kỹ thuật sửa BOM đã chọn cho dòng RFQ bằng cách tạo một bản BOM mới (không sửa trực tiếp BOM chuẩn đang dùng).", "BF-02", ""),
    "UC-071": ("Kỹ thuật xác nhận hoàn tất kết quả xử lý kỹ thuật cho một dòng RFQ.", "", "Có thể chuyển ngay sang dòng kế tiếp"),
    "UC-072": ("Kỹ thuật đánh dấu một dòng RFQ không thể gia công/báo giá, kèm lý do.", "", ""),
    "UC-073": ("Kỹ thuật trả lại RFQ (một hoặc nhiều dòng) cho Sales để bổ sung thông tin còn thiếu.", "", "Đối lập với UC-074"),
    "UC-074": ("Nhân viên Kinh doanh bổ sung thông tin còn thiếu và gửi lại RFQ cho Kỹ thuật xử lý tiếp.", "", ""),
    "UC-075": ("Xem lại toàn bộ diễn biến xử lý của một yêu cầu báo giá.", "", ""),
    "UC-076": ("Nhân viên Kinh doanh hủy một RFQ chưa lên báo giá chính thức.", "", ""),
    "UC-077": ("Truy cập các menu Báo giá / Phê duyệt / Đơn bán hàng (không có màn hub hợp nhất).", "", ""),
    "UC-078": ("Nhân viên Kinh doanh tạo báo giá từ một RFQ đã xử lý xong; hệ thống tự tính giá từng dòng (vật tư + công đoạn + điều chỉnh + markup).", "BF-03", ""),
    "UC-079": ("Nhân viên Kinh doanh điều chỉnh số lượng/đơn giá dòng báo giá ở trạng thái Nháp; hệ thống tự đánh giá lại nhu cầu phê duyệt.", "BF-03, BF-04", ""),
    "UC-080": ("Nhân viên Kinh doanh điều chỉnh chiết khấu và VAT của báo giá; hệ thống gợi ý khoảng cho phép theo nhóm khách hàng.", "BF-03", ""),
    "UC-081": ("Khi dữ liệu giá của báo giá thay đổi, hệ thống tự huỷ yêu cầu phê duyệt cũ (nếu còn) và đánh giá lại theo ma trận giá trị, mức chiết khấu, giá sàn để tạo yêu cầu phê duyệt mới nếu cần.", "BF-04", ""),
    "UC-082": ("Xem phân tích giá thành và cấu phần giá của báo giá: lãi gộp, cơ cấu vật tư/công đoạn/chi phí chung, markup theo giá niêm yết và giá sàn.", "BF-03", ""),
    "UC-083": ("CEO/Trưởng phòng Kinh doanh xử lý hòm Phê duyệt báo giá: danh sách yêu cầu chờ/đã xử lý.", "BF-04", ""),
    "UC-084": ("CEO/Trưởng phòng Kinh doanh duyệt hoặc từ chối (bắt buộc nhập lý do) một yêu cầu phê duyệt báo giá.", "BF-04", ""),
    "UC-085": ("Báo giá tự động chuyển sang Đã duyệt nội bộ ngay khi yêu cầu phê duyệt liên quan được duyệt (không phải thao tác riêng).", "BF-04", "Gộp vào UC-084"),
    "UC-086": ("Nhân viên Kinh doanh gửi báo giá cho khách hàng; hệ thống tự đặt hạn hiệu lực mặc định, đính kèm PDF, cảnh báo thiếu MST/địa chỉ.", "", ""),
    "UC-087": ("Nhân viên Kinh doanh cập nhật kết quả phản hồi của khách: đồng ý, rút lại đồng ý, hoặc từ chối (bắt buộc lý do).", "", ""),
    "UC-087A": ("Ghi nhận yêu cầu điều chỉnh của khách hàng (giá/chiết khấu, vật liệu-kỹ thuật, hoặc giao hàng-điều khoản) và định hướng bước tiếp theo tương ứng.", "", "Có thể chuyển lại cho Kỹ thuật (UC-073)"),
    "UC-088": ("Nhân viên Kinh doanh tạo đơn bán hàng từ báo giá đã được khách đồng ý; snapshot dòng hàng, giá, định mức.", "", ""),
    "UC-089": ("Quản lý vòng đời đơn bán hàng: Nháp → Xác nhận → Hoàn tất/Hủy; xác nhận đơn sẽ tự nâng cấp sản phẩm và khoá BOM liên quan.", "", "Kích hoạt UC-046, UC-092A"),
    "UC-090": ("Sau khi đăng nhập, hệ thống đưa người dùng vào thẳng màn phù hợp với vai trò; hiển thị badge số việc chờ phê duyệt.", "BF-07", ""),
    "UC-090A": ("Thủ kho đăng nhập vào thẳng danh sách các phiếu kho đang chờ xử lý (nhận/kiểm/chuyển/giao) thay vì màn Tồn kho.", "BF-07", "Thay thế UC-090 cho vai trò Thủ kho"),
    "UC-091": ("Thủ kho ghi nhận hàng về từ nhà cung cấp vào khu vực chờ kiểm; hệ thống tự cấp số lô nếu chưa nhập, tự sinh phiếu Kiểm & cất hàng kế tiếp.", "", ""),
    "UC-091A": ("Thủ kho kiểm tra chất lượng hàng nhận: nhập số lượng đạt/loại, lý do loại; hệ thống chặn xác nhận nếu số liệu không hợp lệ hoặc thiếu lô.", "", "Bước 2/2 của UC-091"),
    "UC-091B": ("Mua hàng xử lý phiếu trả nhà cung cấp tự sinh khi Thủ kho phát hiện hàng lỗi ở bước kiểm.", "", "Sinh ra từ UC-091A"),
    "UC-092": ("Thủ kho ghi nhận chuyển vật tư/hàng hoá giữa các khu vực trong kho; có 2 nút tạo nhanh cho 2 tuyến thường dùng.", "", ""),
    "UC-092A": ("Tạo phiếu giao hàng trực tiếp từ đơn bán hàng đã xác nhận; Thủ kho xử lý phiếu, các vai trò khác chỉ bấm nút tạo.", "", "Sau UC-089"),
    "UC-092B": ("Thủ kho cân, ghi nhận và bán phế liệu thu hồi được từ khu vực sản xuất theo giá bán đã niêm yết.", "", ""),
    "UC-092C": ("So sánh khối lượng phế liệu dự toán (tính từ định mức các đơn đã chốt trong kỳ) với khối lượng thực tế đã cân được, theo từng tháng.", "", "Dùng dữ liệu từ UC-044, UC-092B"),
    "UC-093": ("Xem danh sách tồn kho hiện tại theo sản phẩm/lô/vị trí, không hiển thị giá vốn.", "", "Cảnh báo tồn tối thiểu: xem JOB-04, chưa triển khai"),
    "UC-094": ("Thủ kho đếm thực tế và điều chỉnh số lượng tồn kho cho khớp; hệ thống tự sinh chứng từ điều chỉnh.", "", ""),
    "UC-095": ("Kiểm tra vật tư có đủ tồn kho để đáp ứng một BOM ngay khi lập báo giá — chưa triển khai, thuộc backlog giai đoạn sau.", "", ""),
    "UC-096": ("Nhập kho thành phẩm theo BOM khi hoàn tất sản xuất — chưa triển khai, đã seed sẵn loại phiếu nhưng chưa có màn hình/logic.", "", "Thuộc backlog Lệnh sản xuất"),
    "UC-097": ("Tự tính nhu cầu vật tư cho phiếu nhập kho theo BOM — chưa triển khai, gắn với UC-096.", "", ""),
    "UC-099": ("Người dùng đăng xuất khỏi hệ thống.", "", ""),
    "UC-100": ("Người dùng quên mật khẩu nhận email kèm liên kết để tự đặt lại.", "", ""),
    "UC-101": ("Người dùng tự đổi mật khẩu của mình sau khi đăng nhập.", "", ""),
    "UC-102": ("Hệ thống cảnh báo khi cấu hình tham số giá bị thiếu gây lỗi báo giá (chưa cảnh báo đúng nghĩa 'giá trị bất hợp lý' như tên gọi).", "BF-06", "Xem FT-17"),
    "UC-103": ("Khi tạo hoặc sửa khách hàng, hệ thống rà trùng mã số thuế với các khách hàng/NCC khác, cho phép đánh dấu ngoại lệ khi là chi nhánh dùng chung MST.", "", ""),
    "UC-104": ("Quản lý người liên hệ (họ tên, chức vụ, điện thoại, email) gắn với một hồ sơ khách hàng — hiện chưa có ở hồ sơ nhà cung cấp.", "", ""),
    "UC-105": ("Theo dõi trạng thái và % tiến độ xử lý của từng yêu cầu báo giá.", "", ""),
    "UC-106": ("Hệ thống tự tính số ngày chờ xử lý và cảnh báo khi RFQ quá hạn xử lý kỹ thuật.", "", ""),
    "UC-107": ("Nhập điều khoản thương mại (thanh toán, giao hàng...) của báo giá.", "", ""),
    "UC-108": ("Hệ thống cảnh báo khi khách hàng thiếu thông tin bắt buộc (MST, địa chỉ) ngay lúc gửi báo giá.", "", ""),
    "UC-109": ("Đặt/gia hạn hạn hiệu lực báo giá; tự động chuyển sang Hết hiệu lực khi quá hạn mà khách chưa chốt (chạy hằng ngày).", "", "Xem JOB-01"),
    "UC-110": ("Giám sát và nhắc việc (activity) cho người duyệt hợp lệ khi phát sinh yêu cầu phê duyệt báo giá quá hạn.", "BF-04", ""),
    "UC-111": ("Khi tên sản phẩm mới trùng hoặc gần giống một sản phẩm đã có, hệ thống báo cho người dùng biết — hiện chỉ áp dụng khi Kỹ thuật tạo SP gia công/BTP qua RFQ.", "BF-02", ""),
    "UC-112": ("Khi định mức/vật tư chưa có giá nhà cung cấp, hệ thống cảnh báo và giao việc nhắc Mua hàng cập nhật.", "BF-02, BF-08", ""),
    "UC-113": ("Khi một bảng giá nhà cung cấp được áp dụng, hệ thống tự cập nhật lại giá vốn tham chiếu của sản phẩm/vật tư liên quan.", "", "Kích hoạt bởi UC-050"),
    # --- MFG/RPT (chưa triển khai, backlog) ---
    "UC-114": ("Phát lệnh sản xuất từ đơn bán hàng đã chốt theo định mức — chưa triển khai (module Sản xuất chưa có code).", "", "Planned"),
    "UC-115": ("Theo dõi trạng thái lệnh sản xuất — chưa triển khai.", "", "Planned"),
    "UC-116": ("Lập kế hoạch sản xuất theo hạn giao hàng — chưa triển khai.", "", "Planned"),
    "UC-117": ("Tổng quan sản xuất cho quản lý — chưa triển khai.", "", "Planned"),
    "UC-118": ("Bảng tổng quan báo cáo quản trị: báo giá, đơn hàng, sản xuất, tồn kho cho CEO — chưa triển khai (module Báo cáo & Dashboard chưa có code).", "", "Planned"),
}
