{
    "name": "DL-Product",
    "version": "17.0.1.0.0",
    "summary": "Danh mục sản phẩm, Bán thành phẩm, Vật tư - Tích hợp product.product",
    "author": "Dai Linh",
    "category": "Hidden",
    "depends": ["dl_base", "product", "stock", "uom", "dl_partner"],
    "data": [
        "security/ir.model.access.csv",
        "data/product_sequence.xml",
        "data/material_cron.xml",
        "data/material_category_data.xml",
        "data/rbac_features.xml",
        "data/dl_demo_data.xml",
        "views/product_views.xml",
        "views/semi_views.xml",
        "views/category_views.xml",
        "views/material_views.xml",
        "views/menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "dl_product/static/src/scss/product_list.scss",
            "dl_product/static/src/scss/product_form.scss",
            "dl_product/static/src/scss/semi_list.scss",
            "dl_product/static/src/scss/semi_form.scss",
            "dl_product/static/src/scss/category_list.scss",
            "dl_product/static/src/scss/category_form.scss",
            "dl_product/static/src/scss/material_list.scss",
            "dl_product/static/src/scss/material_form.scss",
            "dl_product/static/src/views/product_list_controller.js",
            "dl_product/static/src/views/product_form_controller.js",
            "dl_product/static/src/views/semi_list_controller.js",
            "dl_product/static/src/views/semi_form_controller.js",
            "dl_product/static/src/views/category_list_controller.js",
            "dl_product/static/src/views/category_form_controller.js",
            "dl_product/static/src/views/material_list_controller.js",
            "dl_product/static/src/views/material_form_controller.js",
        ],
    },
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
