{
    "name": "DL-Product",
    "version": "17.0.3.10.0",
    "summary": "Sản phẩm hợp nhất (product.product), bảng giá nhà cung cấp, đo lường - theo Data Model TDS 4",
    "author": "Dai Linh",
    "category": "Hidden",
    "depends": ["dl_base", "product", "stock", "uom", "dl_partner"],
    "data": [
        "security/ir.model.access.csv",
        "data/rbac_features.xml",
        "security/ir_rule.xml",
        # Thứ tự: ĐVT → nhóm chuẩn → seed vật tư (có SCRAP-STEEL) → demo
        # (seed vật tư tham chiếu ĐVT Cây/Tấm/... nên uom_data phải nạp TRƯỚC;
        #  demo tham chiếu seed_scrap_steel nên seed vật tư nạp trước demo).
        "data/uom_data.xml",
        "data/material_category_data.xml",
        "data/material_seed_data.xml",
        "data/dl_demo_data.xml",
        "views/product_views.xml",
        "views/material_views.xml",
        "views/product_pricing_views.xml",
        "views/category_views.xml",
        "views/product_supplierinfo_views.xml",
        "views/measurement_views.xml",
        "views/menus.xml",
        # Sau menus.xml — tham chiếu menu_dl_product_root (sequence, cron, rà soát)
        "data/dl_product_data.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "dl_product/static/src/js/nav_patch.js",
            "dl_product/static/src/scss/product_list.scss",
            "dl_product/static/src/scss/pricing_list.scss",
            "dl_product/static/src/scss/supplierinfo_list.scss",
            "dl_product/static/src/scss/product_form.scss",
            "dl_product/static/src/scss/category_list.scss",
            "dl_product/static/src/views/product_list_controller.js",
            "dl_product/static/src/views/product_form_controller.js",
            "dl_product/static/src/views/category_list_controller.js",
            "dl_product/static/src/views/category_form_controller.js",
            "dl_product/static/src/views/supplierinfo_list_controller.js",
            "dl_product/static/src/views/meastype_form_controller.js",
            "dl_product/static/src/views/measshape_form_controller.js",
            "dl_product/static/src/views/supplierinfo_form_controller.js",
            "dl_product/static/src/components/supplier_price/supplier_price_field.js",
            "dl_product/static/src/components/supplier_price/supplier_price_field.xml",
            "dl_product/static/src/components/alt_supplier/alt_product_field.js",
        ],
    },
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
