{
    "name": "DL-Product",
    "version": "17.0.2.0.0",
    "summary": "Sản phẩm hợp nhất (product.product), bảng giá NCC, đo lường - theo Data Model TDS 4",
    "author": "Dai Linh",
    "category": "Hidden",
    "depends": ["dl_base", "product", "stock", "uom", "dl_partner"],
    "data": [
        "security/ir.model.access.csv",
        "data/rbac_features.xml",
        "security/ir_rule.xml",
        "data/material_category_data.xml",
        "data/dl_demo_data.xml",
        "views/product_views.xml",
        "views/material_views.xml",
        "views/product_pricing_views.xml",
        "views/category_views.xml",
        "views/product_supplierinfo_views.xml",
        "views/measurement_views.xml",
        "views/product_home.xml",
        "views/pricing_home.xml",
        "views/menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "dl_product/static/src/js/nav_patch.js",
            "dl_product/static/src/components/product_home/product_home.scss",
            "dl_product/static/src/components/product_home/product_home.xml",
            "dl_product/static/src/components/product_home/product_home.js",
            "dl_product/static/src/components/pricing_home/pricing_home.scss",
            "dl_product/static/src/components/pricing_home/pricing_home.xml",
            "dl_product/static/src/components/pricing_home/pricing_home.js",
            # abc OWL mock
            "dl_product/static/src/scss/product_list.scss",
            "dl_product/static/src/scss/product_form.scss",
            "dl_product/static/src/scss/category_list.scss",
            "dl_product/static/src/scss/product_kanban.scss",
            "dl_product/static/src/views/product_list_controller.js",
            "dl_product/static/src/views/product_form_controller.js",
            "dl_product/static/src/views/category_list_controller.js",
            "dl_product/static/src/views/category_form_controller.js",
            "dl_product/static/src/views/supplierinfo_list_controller.js",
            "dl_product/static/src/views/product_kanban_controller.js",
            "dl_product/static/src/views/meastype_form_controller.js",
            "dl_product/static/src/views/measshape_form_controller.js",
            "dl_product/static/src/views/supplierinfo_form_controller.js",
        ],
    },
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
